import { ArrowUpRight, CheckCircle2, Leaf, Network, ShieldCheck } from "lucide-react";

const principles = [
  { icon: Leaf, title: "Farmer-first", text: "More reliable quality records mean fairer payouts and fewer disputes at the collection point." },
  { icon: Network, title: "One shared grid", text: "Cooperatives, chillers, fleets, and auditors work from the same live operating picture." },
  { icon: ShieldCheck, title: "Proof by default", text: "Every custody handoff is anchored to a tamper-resistant record anyone can verify." },
];

export default function About() {
  return (
    <div>
      <section className="hero-mesh grid-texture px-4 md:px-8 py-16 md:py-24"><div className="mx-auto max-w-7xl grid lg:grid-cols-2 gap-12 items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#2d8b57]">Built for the milk grid</p><h1 className="mt-4 font-serif text-5xl md:text-6xl leading-[1] tracking-tight text-[#123b2a]">A better record<br />for every <span className="text-[#2d8b57]">drop.</span></h1><p className="mt-6 max-w-xl text-lg text-slate-600 leading-relaxed">DairyChain is a blockchain-anchored cold-chain traceability platform built with Tamil Nadu's dairy cooperatives — making quality visible from farm to fridge.</p></div><div className="relative h-80 rounded-[28px] overflow-hidden photo-frame border-8 border-white/70"><img src="/images/cold-chain-truck.jpg" alt="Refrigerated cold-chain delivery truck" className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#123b2a]/75 to-transparent" /><div className="absolute bottom-5 left-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-white/60">Tamil Nadu Milk Grid</p><p className="mt-1 text-2xl font-serif">From village roads to city doors.</p></div></div></div></section>
      <section className="px-4 md:px-8 py-16 bg-white"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#2d8b57]">Why it exists</p><h2 className="mt-3 font-serif text-4xl text-[#123b2a]">The cold chain is a promise.</h2><p className="mt-4 text-slate-500 leading-relaxed">Every temperature reading, handover, and pasteurization cycle is cryptographically signed and recorded on-chain, giving farmers, processors, regulators, and consumers one immutable record of a batch's journey.</p></div><div className="mt-10 grid md:grid-cols-3 gap-5">{principles.map(({ icon: Icon, title, text }) => <div key={title} className="card-hover rounded-2xl border border-[#dcebe0] bg-[#f8fcf8] p-6"><div className="w-11 h-11 rounded-xl bg-white border border-[#dcebe0] flex items-center justify-center"><Icon className="w-5 h-5 text-[#2d8b57]" /></div><h3 className="mt-5 text-lg font-bold text-[#164d33]">{title}</h3><p className="mt-2 text-sm text-slate-500 leading-relaxed">{text}</p></div>)}</div></div></section>
      <section className="bg-[#f5ead6] px-4 md:px-8 py-16"><div className="mx-auto max-w-3xl text-center"><CheckCircle2 className="mx-auto w-9 h-9 text-[#a57936]" /><h2 className="mt-4 font-serif text-3xl text-[#5a421f]">Developed in partnership with the people who move milk.</h2><p className="mt-4 text-[#80663d] leading-relaxed">The platform is developed in partnership with the Tamil Nadu Milk Federation and a consortium of dairy cooperatives, chilling centers, and logistics providers across the state.</p><a href="/dashboard" className="inline-flex items-center gap-2 mt-7 text-sm font-bold text-[#5a421f] hover:text-[#2d8b57]">Explore the live dashboard <ArrowUpRight className="w-4 h-4" /></a></div></section>
    </div>
  );
}
