import { Link } from "react-router-dom";
import { ArrowDown, ArrowUpRight, Check, Leaf, ScanLine, ShieldCheck, Sparkles, Truck, Waves } from "lucide-react";
import { landingStats } from "../data/mockData.js";

const heroPillars = [
  { icon: Leaf, title: "Origin clarity", text: "See the farm and people behind every batch." },
  { icon: Waves, title: "Cold-chain proof", text: "Follow temperature, not just a promise." },
  { icon: ShieldCheck, title: "Public trust", text: "Verify the record without a wallet." },
];

export default function Landing() {
  return (
    <div className="-mt-16 overflow-hidden">
      <section className="relative flex min-h-[780px] items-center overflow-hidden bg-[#163c2a] text-white md:min-h-screen">
        <img src="/images/dairy-field.jpg" alt="Cows grazing in a dairy field at sunrise" className="hero-photo absolute inset-[-3%] h-[106%] w-[106%] object-cover object-center" />
        <div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(18,45,34,.58)_0%,rgba(18,45,34,.18)_37%,rgba(11,37,26,.8)_100%)]" />
        <div className="hero-light absolute -left-1/4 top-1/4 h-1/2 w-1/2 rounded-full bg-[#f6e1ae]/20 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_42%,rgba(255,244,215,.16),transparent_34%)]" />
        <div className="pointer-events-none absolute inset-0 overflow-hidden"><span className="particle absolute bottom-32 left-[23%] h-1.5 w-1.5 rounded-full bg-[#f6e1ae]/60" /><span className="particle particle-delay-1 absolute bottom-24 left-[64%] h-1 w-1 rounded-full bg-white/70" /><span className="particle particle-delay-2 absolute bottom-40 left-[74%] h-2 w-2 rounded-full bg-[#b9f2c7]/60" /><span className="particle particle-delay-3 absolute bottom-28 left-[38%] h-1 w-1 rounded-full bg-white/60" /></div>
        <div className="absolute left-6 top-1/2 hidden -translate-y-1/2 -rotate-90 items-center gap-3 text-[10px] font-bold uppercase tracking-[.28em] text-white/65 lg:flex"><span className="h-px w-12 bg-white/50" /> Tamil Nadu · 2025 / 26</div>

        <div className="relative z-10 mx-auto w-full max-w-7xl px-5 pb-28 pt-36 text-center md:px-10 md:pb-36 md:pt-44">
          <div className="mx-auto flex w-fit items-center gap-2 rounded-full border border-white/35 bg-white/10 px-3.5 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-white/90 backdrop-blur-md reveal"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#b9f2c7]" /> The living record of milk</div>
          <h1 className="mx-auto mt-7 max-w-5xl font-serif text-[52px] leading-[.96] tracking-[-.045em] text-white drop-shadow-md md:text-[92px]">Good milk has<br /><span className="italic text-[#f6e1ae]">a story worth proving.</span></h1>
          <p className="mx-auto mt-7 max-w-xl text-sm leading-relaxed text-white/80 md:text-base">DairyChain turns every handoff, chill, and delivery into a journey customers can see — from the first pour in Erode to the final shelf in Chennai.</p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-3"><Link to="/scan" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-[#164d33] shadow-2xl shadow-black/15 hover:-translate-y-1 hover:bg-[#f6e1ae]">Scan a carton <ScanLine className="h-4 w-4" /></Link><Link to="/dashboard" className="inline-flex items-center gap-2 rounded-xl border border-white/55 bg-white/10 px-5 py-3.5 text-sm font-bold text-white backdrop-blur-md hover:bg-white/20">Explore the grid <ArrowUpRight className="h-4 w-4" /></Link></div>

          <div className="mx-auto mt-16 grid max-w-4xl gap-3 text-left md:grid-cols-3">{heroPillars.map(({ icon: Icon, title, text }, index) => <div key={title} className="group rounded-2xl border border-white/20 bg-black/10 p-4 backdrop-blur-md transition hover:-translate-y-1 hover:bg-black/20"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/15 text-[#f6e1ae]"><Icon className="h-4 w-4" /></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/55">0{index + 1}</p><p className="text-sm font-bold text-white">{title}</p></div></div><p className="mt-3 pl-12 text-xs leading-relaxed text-white/65">{text}</p></div>)}</div>
        </div>

        <div className="absolute bottom-5 left-5 right-5 z-10 mx-auto flex max-w-7xl flex-col gap-3 border-t border-white/25 pt-4 text-[10px] font-bold uppercase tracking-[.14em] text-white/65 md:bottom-7 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-x-6 gap-y-2"><span className="inline-flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#b9f2c7]" /> 500+ farms connected</span><span className="inline-flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#f6e1ae]" /> 10,000+ proofs anchored</span><span className="inline-flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-white" /> 2°–6°C protected</span></div><span className="hidden items-center gap-2 md:flex">Scroll to discover <ArrowDown className="h-3.5 w-3.5" /></span></div>
      </section>

      <section className="bg-[#f7f4eb] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#2d8b57]">A calmer kind of confidence</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-[1.02] tracking-tight text-[#164d33] md:text-6xl">The details are the difference.</h2></div><p className="max-w-lg text-slate-600 leading-relaxed">The people moving milk already do the hard work. DairyChain makes the invisible moments legible — so quality earns trust, and trust travels further.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{landingStats.map((stat, index) => <div key={stat.label} className="card-hover rounded-2xl border border-[#dfdfd2] bg-white/70 p-6"><div className="flex items-start justify-between"><span className="font-mono text-[10px] text-[#2d8b57]">0{index + 1}</span><Sparkles className="h-4 w-4 text-[#b99b5a]" /></div><p className="mt-8 font-serif text-4xl text-[#164d33]">{stat.value}</p><p className="mt-2 text-sm font-bold text-[#164d33]">{stat.label}</p><p className="mt-2 text-sm leading-relaxed text-slate-500">{stat.description}</p></div>)}</div></div></section>

      <section className="bg-white px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 border-b border-[#dcebe0] pb-8 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#2d8b57]">Built for real hands</p><h2 className="mt-3 font-serif text-4xl text-[#164d33] md:text-5xl">One journey. Many guardians.</h2></div><Link to="/about" className="inline-flex items-center gap-2 text-sm font-bold text-[#2d8b57] hover:text-[#164d33]">How the consortium works <ArrowUpRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="relative overflow-hidden rounded-[26px] bg-[#164d33] p-2 shadow-xl"><img src="/images/collection-center.jpg" alt="Dairy cooperative collection center" className="h-[360px] w-full rounded-[20px] object-cover opacity-90" /><div className="absolute inset-2 rounded-[20px] bg-gradient-to-t from-[#123b2a]/80 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 text-white"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/60">Proof point / Erode 04</p><p className="mt-2 font-serif text-2xl">Where good systems start.</p></div></div><div className="space-y-5">{heroPillars.map(({ icon: Icon, title, text }, index) => <div key={title} className="flex gap-4 border-b border-[#e6efe7] pb-5 last:border-0"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#eff9f1] text-[#2d8b57]"><Icon className="h-5 w-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">0{index + 1} / promise</p><h3 className="mt-1 text-lg font-bold text-[#164d33]">{title}</h3><p className="mt-1 text-sm leading-relaxed text-slate-500">{text}</p></div><Check className="ml-auto mt-1 h-4 w-4 shrink-0 text-[#36a866]" /></div>)}</div></div></div></section>

      <section className="bg-[#164d33] px-5 py-20 text-center text-white md:px-10 md:py-24"><Truck className="mx-auto h-8 w-8 text-[#f6e1ae]" /><h2 className="mx-auto mt-5 max-w-3xl font-serif text-4xl leading-tight md:text-5xl">Make the journey part of the product.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-white/65">Give every customer a simple, beautiful way to verify where their milk came from and how it travelled.</p><Link to="/scan" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#f6e1ae] px-5 py-3.5 text-sm font-bold text-[#164d33] hover:bg-white">Open the customer scanner <ScanLine className="h-4 w-4" /></Link></section>
    </div>
  );
}
